include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/.dart_tool/**"
    - "**/build/**"
  language:
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
