name: rendercore
description: RenderCore library (app-agnostic)
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.2

flutter:
  # NO assets here. RC is a library only.
