name: CI (RenderCore library)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Dart/Flutter deps
        run: dart pub get
      - name: Analyze library
        run: flutter analyze lib/rendercore
      - name: Run tests (unit only)
        run: flutter test --coverage