name: ci

on:
  pull_request:
    branches: [ "main", "rc/dev" ]
  push:
    branches: [ "rc/dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Pub get
        run: dart pub get --no-example
      - name: Analyze
        run: flutter analyze lib/rendercore
      - name: Unit tests (if any)
        run: |
          if [ -d "test" ]; then
            flutter test --no-pub || exit 1
          else
            echo "No tests/ directory yet, skipping"
          fi
